import {MigrationInterface, QueryRunner} from "typeorm";

export class FakeProducts1634499994083 implements MigrationInterface {
    
    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`
        insert into product (name, price, quantity, description) values ('Baguettes', 9.99, 5, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ante elit, malesuada at dui in, tincidunt venenatis leo. Duis fringilla leo nulla, ac porta eros tincidunt vitae. Nunc id dolor euismod, vehicula elit vel, iaculis est. Curabitur eu maximus mauris, sed molestie libero. Nam nulla mauris, viverra ac urna sed, gravida gravida mi. Pellentesque ultrices, ante vitae bibendum hendrerit, sapien nibh molestie arcu, sit amet tincidunt nunc purus mollis tortor. Aenean pharetra elementum risus, vitae sodales nunc blandit eu. Duis pharetra molestie orci, nec pellentesque nulla.');
        insert into product (name, price, quantity, description) values ('Croissant', 9.99, 5, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ante elit, malesuada at dui in, tincidunt venenatis leo. Duis fringilla leo nulla, ac porta eros tincidunt vitae. Nunc id dolor euismod, vehicula elit vel, iaculis est. Curabitur eu maximus mauris, sed molestie libero. Nam nulla mauris, viverra ac urna sed, gravida gravida mi. Pellentesque ultrices, ante vitae bibendum hendrerit, sapien nibh molestie arcu, sit amet tincidunt nunc purus mollis tortor. Aenean pharetra elementum risus, vitae sodales nunc blandit eu. Duis pharetra molestie orci, nec pellentesque nulla.');
        insert into product (name, price, quantity, description) values ('Sour Dough', 9.99, 5, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ante elit, malesuada at dui in, tincidunt venenatis leo. Duis fringilla leo nulla, ac porta eros tincidunt vitae. Nunc id dolor euismod, vehicula elit vel, iaculis est. Curabitur eu maximus mauris, sed molestie libero. Nam nulla mauris, viverra ac urna sed, gravida gravida mi. Pellentesque ultrices, ante vitae bibendum hendrerit, sapien nibh molestie arcu, sit amet tincidunt nunc purus mollis tortor. Aenean pharetra elementum risus, vitae sodales nunc blandit eu. Duis pharetra molestie orci, nec pellentesque nulla.');
        insert into product (name, price, quantity, description) values ('Sandwich Bread', 9.99, 5, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ante elit, malesuada at dui in, tincidunt venenatis leo. Duis fringilla leo nulla, ac porta eros tincidunt vitae. Nunc id dolor euismod, vehicula elit vel, iaculis est. Curabitur eu maximus mauris, sed molestie libero. Nam nulla mauris, viverra ac urna sed, gravida gravida mi. Pellentesque ultrices, ante vitae bibendum hendrerit, sapien nibh molestie arcu, sit amet tincidunt nunc purus mollis tortor. Aenean pharetra elementum risus, vitae sodales nunc blandit eu. Duis pharetra molestie orci, nec pellentesque nulla.');
        insert into product (name, price, quantity, description) values ('Pretzels', 9.99, 5, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ante elit, malesuada at dui in, tincidunt venenatis leo. Duis fringilla leo nulla, ac porta eros tincidunt vitae. Nunc id dolor euismod, vehicula elit vel, iaculis est. Curabitur eu maximus mauris, sed molestie libero. Nam nulla mauris, viverra ac urna sed, gravida gravida mi. Pellentesque ultrices, ante vitae bibendum hendrerit, sapien nibh molestie arcu, sit amet tincidunt nunc purus mollis tortor. Aenean pharetra elementum risus, vitae sodales nunc blandit eu. Duis pharetra molestie orci, nec pellentesque nulla.');
        insert into product (name, price, quantity, description) values ('Garlic Bread', 9.99, 5, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ante elit, malesuada at dui in, tincidunt venenatis leo. Duis fringilla leo nulla, ac porta eros tincidunt vitae. Nunc id dolor euismod, vehicula elit vel, iaculis est. Curabitur eu maximus mauris, sed molestie libero. Nam nulla mauris, viverra ac urna sed, gravida gravida mi. Pellentesque ultrices, ante vitae bibendum hendrerit, sapien nibh molestie arcu, sit amet tincidunt nunc purus mollis tortor. Aenean pharetra elementum risus, vitae sodales nunc blandit eu. Duis pharetra molestie orci, nec pellentesque nulla.');
        insert into product (name, price, quantity, description) values ('Dinner Rolls', 9.99, 5, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ante elit, malesuada at dui in, tincidunt venenatis leo. Duis fringilla leo nulla, ac porta eros tincidunt vitae. Nunc id dolor euismod, vehicula elit vel, iaculis est. Curabitur eu maximus mauris, sed molestie libero. Nam nulla mauris, viverra ac urna sed, gravida gravida mi. Pellentesque ultrices, ante vitae bibendum hendrerit, sapien nibh molestie arcu, sit amet tincidunt nunc purus mollis tortor. Aenean pharetra elementum risus, vitae sodales nunc blandit eu. Duis pharetra molestie orci, nec pellentesque nulla.');
        insert into product (name, price, quantity, description) values ('Croquettes', 9.99, 5, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ante elit, malesuada at dui in, tincidunt venenatis leo. Duis fringilla leo nulla, ac porta eros tincidunt vitae. Nunc id dolor euismod, vehicula elit vel, iaculis est. Curabitur eu maximus mauris, sed molestie libero. Nam nulla mauris, viverra ac urna sed, gravida gravida mi. Pellentesque ultrices, ante vitae bibendum hendrerit, sapien nibh molestie arcu, sit amet tincidunt nunc purus mollis tortor. Aenean pharetra elementum risus, vitae sodales nunc blandit eu. Duis pharetra molestie orci, nec pellentesque nulla.');

        insert into product (name, price, quantity, description) values ('Broccoli', 9.99, 5, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ante elit, malesuada at dui in, tincidunt venenatis leo. Duis fringilla leo nulla, ac porta eros tincidunt vitae. Nunc id dolor euismod, vehicula elit vel, iaculis est. Curabitur eu maximus mauris, sed molestie libero. Nam nulla mauris, viverra ac urna sed, gravida gravida mi. Pellentesque ultrices, ante vitae bibendum hendrerit, sapien nibh molestie arcu, sit amet tincidunt nunc purus mollis tortor. Aenean pharetra elementum risus, vitae sodales nunc blandit eu. Duis pharetra molestie orci, nec pellentesque nulla.');
        insert into product (name, price, quantity, description) values ('Cabbage', 9.99, 5, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ante elit, malesuada at dui in, tincidunt venenatis leo. Duis fringilla leo nulla, ac porta eros tincidunt vitae. Nunc id dolor euismod, vehicula elit vel, iaculis est. Curabitur eu maximus mauris, sed molestie libero. Nam nulla mauris, viverra ac urna sed, gravida gravida mi. Pellentesque ultrices, ante vitae bibendum hendrerit, sapien nibh molestie arcu, sit amet tincidunt nunc purus mollis tortor. Aenean pharetra elementum risus, vitae sodales nunc blandit eu. Duis pharetra molestie orci, nec pellentesque nulla.');
        insert into product (name, price, quantity, description) values ('Carrots', 9.99, 5, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ante elit, malesuada at dui in, tincidunt venenatis leo. Duis fringilla leo nulla, ac porta eros tincidunt vitae. Nunc id dolor euismod, vehicula elit vel, iaculis est. Curabitur eu maximus mauris, sed molestie libero. Nam nulla mauris, viverra ac urna sed, gravida gravida mi. Pellentesque ultrices, ante vitae bibendum hendrerit, sapien nibh molestie arcu, sit amet tincidunt nunc purus mollis tortor. Aenean pharetra elementum risus, vitae sodales nunc blandit eu. Duis pharetra molestie orci, nec pellentesque nulla.');
        insert into product (name, price, quantity, description) values ('Celery', 9.99, 5, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ante elit, malesuada at dui in, tincidunt venenatis leo. Duis fringilla leo nulla, ac porta eros tincidunt vitae. Nunc id dolor euismod, vehicula elit vel, iaculis est. Curabitur eu maximus mauris, sed molestie libero. Nam nulla mauris, viverra ac urna sed, gravida gravida mi. Pellentesque ultrices, ante vitae bibendum hendrerit, sapien nibh molestie arcu, sit amet tincidunt nunc purus mollis tortor. Aenean pharetra elementum risus, vitae sodales nunc blandit eu. Duis pharetra molestie orci, nec pellentesque nulla.');
        insert into product (name, price, quantity, description) values ('Onions', 9.99, 5, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ante elit, malesuada at dui in, tincidunt venenatis leo. Duis fringilla leo nulla, ac porta eros tincidunt vitae. Nunc id dolor euismod, vehicula elit vel, iaculis est. Curabitur eu maximus mauris, sed molestie libero. Nam nulla mauris, viverra ac urna sed, gravida gravida mi. Pellentesque ultrices, ante vitae bibendum hendrerit, sapien nibh molestie arcu, sit amet tincidunt nunc purus mollis tortor. Aenean pharetra elementum risus, vitae sodales nunc blandit eu. Duis pharetra molestie orci, nec pellentesque nulla.');
        insert into product (name, price, quantity, description) values ('Garlic', 9.99, 5, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ante elit, malesuada at dui in, tincidunt venenatis leo. Duis fringilla leo nulla, ac porta eros tincidunt vitae. Nunc id dolor euismod, vehicula elit vel, iaculis est. Curabitur eu maximus mauris, sed molestie libero. Nam nulla mauris, viverra ac urna sed, gravida gravida mi. Pellentesque ultrices, ante vitae bibendum hendrerit, sapien nibh molestie arcu, sit amet tincidunt nunc purus mollis tortor. Aenean pharetra elementum risus, vitae sodales nunc blandit eu. Duis pharetra molestie orci, nec pellentesque nulla.');
        insert into product (name, price, quantity, description) values ('Green Beans', 9.99, 5, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ante elit, malesuada at dui in, tincidunt venenatis leo. Duis fringilla leo nulla, ac porta eros tincidunt vitae. Nunc id dolor euismod, vehicula elit vel, iaculis est. Curabitur eu maximus mauris, sed molestie libero. Nam nulla mauris, viverra ac urna sed, gravida gravida mi. Pellentesque ultrices, ante vitae bibendum hendrerit, sapien nibh molestie arcu, sit amet tincidunt nunc purus mollis tortor. Aenean pharetra elementum risus, vitae sodales nunc blandit eu. Duis pharetra molestie orci, nec pellentesque nulla.');

        insert into product (name, price, quantity, description) values ('Pork Belly', 9.99, 5, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ante elit, malesuada at dui in, tincidunt venenatis leo. Duis fringilla leo nulla, ac porta eros tincidunt vitae. Nunc id dolor euismod, vehicula elit vel, iaculis est. Curabitur eu maximus mauris, sed molestie libero. Nam nulla mauris, viverra ac urna sed, gravida gravida mi. Pellentesque ultrices, ante vitae bibendum hendrerit, sapien nibh molestie arcu, sit amet tincidunt nunc purus mollis tortor. Aenean pharetra elementum risus, vitae sodales nunc blandit eu. Duis pharetra molestie orci, nec pellentesque nulla.');
        insert into product (name, price, quantity, description) values ('Steak', 9.99, 5, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ante elit, malesuada at dui in, tincidunt venenatis leo. Duis fringilla leo nulla, ac porta eros tincidunt vitae. Nunc id dolor euismod, vehicula elit vel, iaculis est. Curabitur eu maximus mauris, sed molestie libero. Nam nulla mauris, viverra ac urna sed, gravida gravida mi. Pellentesque ultrices, ante vitae bibendum hendrerit, sapien nibh molestie arcu, sit amet tincidunt nunc purus mollis tortor. Aenean pharetra elementum risus, vitae sodales nunc blandit eu. Duis pharetra molestie orci, nec pellentesque nulla.');
        insert into product (name, price, quantity, description) values ('Ham', 9.99, 5, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ante elit, malesuada at dui in, tincidunt venenatis leo. Duis fringilla leo nulla, ac porta eros tincidunt vitae. Nunc id dolor euismod, vehicula elit vel, iaculis est. Curabitur eu maximus mauris, sed molestie libero. Nam nulla mauris, viverra ac urna sed, gravida gravida mi. Pellentesque ultrices, ante vitae bibendum hendrerit, sapien nibh molestie arcu, sit amet tincidunt nunc purus mollis tortor. Aenean pharetra elementum risus, vitae sodales nunc blandit eu. Duis pharetra molestie orci, nec pellentesque nulla.');
        insert into product (name, price, quantity, description) values ('Chicken', 9.99, 5, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ante elit, malesuada at dui in, tincidunt venenatis leo. Duis fringilla leo nulla, ac porta eros tincidunt vitae. Nunc id dolor euismod, vehicula elit vel, iaculis est. Curabitur eu maximus mauris, sed molestie libero. Nam nulla mauris, viverra ac urna sed, gravida gravida mi. Pellentesque ultrices, ante vitae bibendum hendrerit, sapien nibh molestie arcu, sit amet tincidunt nunc purus mollis tortor. Aenean pharetra elementum risus, vitae sodales nunc blandit eu. Duis pharetra molestie orci, nec pellentesque nulla.');
        insert into product (name, price, quantity, description) values ('Sausage', 9.99, 5, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ante elit, malesuada at dui in, tincidunt venenatis leo. Duis fringilla leo nulla, ac porta eros tincidunt vitae. Nunc id dolor euismod, vehicula elit vel, iaculis est. Curabitur eu maximus mauris, sed molestie libero. Nam nulla mauris, viverra ac urna sed, gravida gravida mi. Pellentesque ultrices, ante vitae bibendum hendrerit, sapien nibh molestie arcu, sit amet tincidunt nunc purus mollis tortor. Aenean pharetra elementum risus, vitae sodales nunc blandit eu. Duis pharetra molestie orci, nec pellentesque nulla.');
        insert into product (name, price, quantity, description) values ('Ground Beef', 9.99, 5, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ante elit, malesuada at dui in, tincidunt venenatis leo. Duis fringilla leo nulla, ac porta eros tincidunt vitae. Nunc id dolor euismod, vehicula elit vel, iaculis est. Curabitur eu maximus mauris, sed molestie libero. Nam nulla mauris, viverra ac urna sed, gravida gravida mi. Pellentesque ultrices, ante vitae bibendum hendrerit, sapien nibh molestie arcu, sit amet tincidunt nunc purus mollis tortor. Aenean pharetra elementum risus, vitae sodales nunc blandit eu. Duis pharetra molestie orci, nec pellentesque nulla.');

        insert into product (name, price, quantity, description) values ('Yogurt', 9.99, 5, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ante elit, malesuada at dui in, tincidunt venenatis leo. Duis fringilla leo nulla, ac porta eros tincidunt vitae. Nunc id dolor euismod, vehicula elit vel, iaculis est. Curabitur eu maximus mauris, sed molestie libero. Nam nulla mauris, viverra ac urna sed, gravida gravida mi. Pellentesque ultrices, ante vitae bibendum hendrerit, sapien nibh molestie arcu, sit amet tincidunt nunc purus mollis tortor. Aenean pharetra elementum risus, vitae sodales nunc blandit eu. Duis pharetra molestie orci, nec pellentesque nulla.');
        insert into product (name, price, quantity, description) values ('Milk', 9.99, 5, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ante elit, malesuada at dui in, tincidunt venenatis leo. Duis fringilla leo nulla, ac porta eros tincidunt vitae. Nunc id dolor euismod, vehicula elit vel, iaculis est. Curabitur eu maximus mauris, sed molestie libero. Nam nulla mauris, viverra ac urna sed, gravida gravida mi. Pellentesque ultrices, ante vitae bibendum hendrerit, sapien nibh molestie arcu, sit amet tincidunt nunc purus mollis tortor. Aenean pharetra elementum risus, vitae sodales nunc blandit eu. Duis pharetra molestie orci, nec pellentesque nulla.');
        insert into product (name, price, quantity, description) values ('Cheese', 9.99, 5, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ante elit, malesuada at dui in, tincidunt venenatis leo. Duis fringilla leo nulla, ac porta eros tincidunt vitae. Nunc id dolor euismod, vehicula elit vel, iaculis est. Curabitur eu maximus mauris, sed molestie libero. Nam nulla mauris, viverra ac urna sed, gravida gravida mi. Pellentesque ultrices, ante vitae bibendum hendrerit, sapien nibh molestie arcu, sit amet tincidunt nunc purus mollis tortor. Aenean pharetra elementum risus, vitae sodales nunc blandit eu. Duis pharetra molestie orci, nec pellentesque nulla.');
        insert into product (name, price, quantity, description) values ('Butter', 9.99, 5, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ante elit, malesuada at dui in, tincidunt venenatis leo. Duis fringilla leo nulla, ac porta eros tincidunt vitae. Nunc id dolor euismod, vehicula elit vel, iaculis est. Curabitur eu maximus mauris, sed molestie libero. Nam nulla mauris, viverra ac urna sed, gravida gravida mi. Pellentesque ultrices, ante vitae bibendum hendrerit, sapien nibh molestie arcu, sit amet tincidunt nunc purus mollis tortor. Aenean pharetra elementum risus, vitae sodales nunc blandit eu. Duis pharetra molestie orci, nec pellentesque nulla.');
        `)
    }

    public async down(_: QueryRunner): Promise<void> {
    }

}
